services:
  postgres:
    image: postgres:17
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - local_pgdata:/var/lib/postgresql/data
      
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@insa-lyon.fr
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_PROXY_X_HOST_COUNT: 1
      PGADMIN_CONFIG_PROXY_X_PREFIX_COUNT: 1
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  notebook:
      image: tomma/dbdm-notebook
      ports:
        - 8888:8888
      volumes:
        - ./:/home/jovyan/work/
      environment:
        - GRANT_SUDO=yes
volumes:
  local_pgdata:
  pgadmin-data:
