version: "3"

services:
  postgres:
    image: postgres
    restart: always
    ports:
        - 5432:5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  pgadmin:
    image: elestio/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80" # type localhost:5050 to your browser to access the UI
  notebook:
    build: notebook/
    ports:
      - 8888:8888
    volumes:
       - ./database/:/home/jovyan/work/database
       - ./datamining/:/home/jovyan/work/datamining
    environment:
      - GRANT_SUDO=yes
      
